// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ckhkmempzhluwtufltdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNraGttZW1wemhsdXd0dWZsdGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjUwMTAsImV4cCI6MjA3MzM0MTAxMH0.PgFpaKczMbxLbdIMXVYYYxVHFWGAL-kc4uN9sMLBrxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);